### PR TITLE
add os_agent & os_contract

### PR DESCRIPTION
**Pull request by ashleykasim**

### CODE REVIEW

**Comment by Roshan2017** [comment]
I signed it!

**Comment by ewiseblatt** [comment]
It turns out the error thing is ok. I havent reviewed this again since you made your changes. I'll get to it by morning.

**Comment by ewiseblatt** [comment]
I am going to merge this. The github check error seems to be a problem on our end because of the multiple authors.

I do have a suggestion while testing your agent against openstack. You might want to check for some of the environment variables that you expect are set and raise an explicit error if they are missing. But I think only if in fact they are required. For example I forgot to set them and got an error back from openstack cli
ValueError: Missing value auth-url required for auth plugin password.

We can fix this in another PR since it isnt clear what, if any, checks to perform.

**Comment by Roshan2017** [comment]
Okay!

**Comment by ewiseblatt** [comment]
Actually, before I merge this, can you squash it?

And also run pylint on it and fix the formatting errors. You can address the others if you want if the suggestions make sense. I'm not strict about it. I'm not sure why the missing method errors are there. It's ok. I think it has something to do with assumptions in the disjunction where the object is created in the base class. It isnt a problem in practice.

pylint --rcfile=pylint.rc citest/openstack_testing/os_agent.py citest/openstack_testing/os_contract.py

**Comment by ashleykasim** [comment]
@ewiseblatt squashed it, should be ready to go.

**Comment by ewiseblatt** [comment]
Does this need python-openstackclient in requirements.txt?
It doesnt look like a static dependency to parse, but you need it for openstack to run, right?

**Comment by ewiseblatt** [comment]
or do you want to leave it out since there are other client options?

**Comment by ewiseblatt** [comment]
if you leave it out, add something into the readme about how to obtain a client.

**Comment by Roshan2017** [comment]
I have added that in README at spinnaker/testing/citest under "Install Platform Dependencies" section

**Comment by ewiseblatt** [comment]
did you push the update (squash first) since I'm ready to merge.

**Comment by Roshan2017** [comment]
@ashleykasim has squashed and pushed the citest changes and I have squashed and pushed spinnaker changes. Also, created a PR https://github.com/spinnaker/spinnaker/pull/1496

**Comment by ewiseblatt** [comment]
Thanks for doing this.

**Pull request merged**
